name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # Ajout de permissions pour le push

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Utilise v3 au lieu de v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' 

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build project
      run: npm run build 

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        publish_branch: gh-pages  # S'assurer que le déploiement se fait sur gh-pages
